linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - goerr113
    - gomnd
    - lll
    - nlreturn
    - wsl
    - varnamelen
    # Deprecated
    - scopelint
    - golint
    - gomoddirectives
    - interfacer
    - maligned
    - varcheck
    - deadcode
    - structcheck
    - nosnakecase
    - ifshort
    - musttag
    # Disabled because of generics
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - maligned
        - paralleltest
        - testpackage

linters-settings:
  tagliatelle:
    case:
      rules:
        json: camel
        yaml: snake
