linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - goerr113
    - gomnd
    - lll
    - nlreturn
    - wsl
    - scopelint # deprecated
    - golint # deprecated
    - gomoddirectives # deprecated
    - interfacer # deprecated
    - maligned # deprecated

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - maligned
        - paralleltest
        - testpackage

linters-settings:
  tagliatelle:
    case:
      rules:
        json: camel
        yaml: snake
